export const baseUrl = "https://api.bikyensub.com.ng";

export const endPoints = {
  login: `${baseUrl}/login.php`,
  verifyToken: `${baseUrl}/verifyToken.php`,
  register: `${baseUrl}/register.php`,
  resetPassword: `${baseUrl}/resetPassword.php`,
  getBalance: `${baseUrl}/getBalance.php`,
  detectNetwork: `${baseUrl}/detectNetwork.php`,
  buyAirtime: `${baseUrl}/buyAirtime.php`,
  registerCAC: `${baseUrl}/cacRegistration.php`,
  companyCAC: `${baseUrl}/companyCac.php`,
  getCACBusinessNames: `${baseUrl}/getCacBusinessNames.php`,
  getCACCompanyReg: `${baseUrl}/getCacCompanyReg.php`,
  getDataTypes: `${baseUrl}/getDataTypes.php`,
  getDataPlans: `${baseUrl}/getDataPlans.php`,
  getOtherData: `${baseUrl}/getOtherData.php`,
  buyData: `${baseUrl}/buyData.php`,
  buyOtherData: `${baseUrl}/buyOtherData.php`,
  validateMeter: `${baseUrl}/validateMeter.php`,
  purchaseElectricity: `${baseUrl}/purchaseElectricity.php`,
  buyEducationPin: `${baseUrl}/buyEducationPin.php`,
  getTransactions: `${baseUrl}/getTransactions.php`,
  getAccountDetails: `${baseUrl}/getAccountDetails.php`,
  fingerPrintSetting: `${baseUrl}/fingerPrintSetting.php`,
  setPassword: `${baseUrl}/setPasswords.php`,
  setPin: `${baseUrl}/setPin.php`,
  getTVPlans: `${baseUrl}/getTvPlans.php`,
  verifySmartCard: `${baseUrl}/verifySmartCard.php`,
  tvSub: `${baseUrl}/tvSub.php`,
  kyc: `${baseUrl}/api.php?action=submit_kyc`,
  getReferralInfo: `${baseUrl}/api.php?action=referral`,
  getReferralStats: `${baseUrl}/api.php?action=get_referral_stats`,
  getAllNotifications: `${baseUrl}/api.php?action=notifications`,
  getUnreadNotificationCount: `${baseUrl}/api.php?action=get_unread_count`,
  markNotificationAsRead: `${baseUrl}/api.php?action=mark_notification_read`,
  markAllNotificationsAsRead: `${baseUrl}/api.php?action=mark_all_notifications_read`,
  profile: `${baseUrl}/api.php?action=profile`,
  pushNotification: `${baseUrl}/saveDeviceToken.php`,
};
